In [1]:
import pandas as pd
excel = pd.ExcelFile('DataSet1.xlsx')
FixCost = pd.read_excel(excel,'Fix Cost')
MatrixCost = pd.read_excel(excel,'Matrix Cost')
Demand = pd.read_excel(excel,'DemandNode')

# Reading Files

In [2]:
excel = pd.ExcelFile('DataSet1-Production.xlsx')
Availability = pd.read_excel(excel,'Availability')
Shift = pd.read_excel(excel,'Shift', usecols ="A:O")
CostShift = pd.read_excel(excel,'Shift', usecols ="P:P")
sales = pd.read_excel(excel,'sales')
salesbehavior = pd.read_excel(excel,'sales behavior')

In [3]:
Availability

Employee  S1  S2  S3  S4  S5  S6  S7  S8  S9  S10  S11  S12  S13  S14  \
0          1   1   1   1   1   1   1   1   0   0    0    0    0    0    0   
1          2   1   1   1   1   0   1   1   0   0    0    0    0    0    0   
2          3   1   1   1   1   1   1   1   0   0    0    0    0    0    0   
3          4   0   0   1   1   1   1   1   0   0    0    0    0    0    0   
4          5   0   0   0   0   0   0   0   0   0    0    0    0    0    0   
5          6   1   0   0   1   1   1   0   0   0    0    0    0    0    0   
6          7   1   0   1   0   0   0   0   0   0    0    0    0    0    0   
7          8   0   0   0   1   0   1   0   0   0    0    0    0    0    0   
8          9   0   1   0   1   0   0   1   0   0    0    0    0    0    0   
9         10   0   0   0   0   0   1   0   0   0    0    0    0    0    0   
10        11   0   0   0   0   0   0   0   1   1    1    0    1    1    1   
11        12   0   0   0   0   0   0   0   1   1    0    1    1    1    1   
12        13   0   0   0   0   0   0   0   1   1    1    1    0    1    1   
13        14   0   0   0   0   0   0   0   1   1    1    1    0    1    0   

    S15  S16  S17  S18  
0     0    0    0    0  
1     0    0    0    0  
2     0    0    0    0  
3     0    0    0    0  
4     0    0    0    0  
5     0    0    0    0  
6     0    0    0    0  
7     0    0    0    0  
8     0    0    0    0  
9     0    0    0    0  
10    1    1    1    1  
11    0    1    1    1  
12    1    1    1    1  
13    1    0    1    1

In [4]:
Shift

Shift  H8  H9  H10  H11  H12  H13  H14  H15  H16  H17  H18  H19  H20  H21
0     S1   1   1    1    1    0    1    1    1    1    0    0    0    0    0
1     S2   0   1    1    1    1    0    1    1    1    1    0    0    0    0
2     S3   0   0    1    1    1    1    0    1    1    1    1    0    0    0
3     S4   0   0    0    1    1    1    1    0    1    1    1    1    0    0
4     S5   0   0    0    0    1    1    1    1    1    1    1    1    0    0
5     S6   0   0    0    0    0    1    1    1    1    1    1    1    1    0
6     S7   0   0    0    0    0    0    1    1    1    1    1    1    1    1
7     S8   1   1    1    1    0    0    0    0    0    0    0    0    0    0
8     S9   0   1    1    1    1    0    0    0    0    0    0    0    0    0
9    S10   0   0    1    1    1    1    0    0    0    0    0    0    0    0
10   S11   0   0    0    1    1    1    1    0    0    0    0    0    0    0
11   S12   0   0    0    0    1    1    1    1    0    0    0    0    0    0
12   S13   0   0    0    0    0    1    1    1    1    0    0    0    0    0
13   S14   0   0    0    0    0    0    1    1    1    1    0    0    0    0
14   S15   0   0    0    0    0    0    0    1    1    1    1    0    0    0
15   S16   0   0    0    0    0    0    0    0    1    1    1    1    0    0
16   S17   0   0    0    0    0    0    0    0    0    1    1    1    1    0
17   S18   0   0    0    0    0    0    0    0    0    0    1    1    1    1

In [5]:
CostShift

Shift Cost
0           40
1           40
2           40
3           40
4           40
5           40
6           40
7           20
8           20
9           20
10          20
11          20
12          20
13          20
14          20
15          20
16          20
17          20

In [6]:
sales.head()

Date   Week Day  Week  Sales
0 2018-03-04    domingo     1  44889
1 2018-03-05      lunes     1  17585
2 2018-03-06     martes     1  20017
3 2018-03-07  miércoles     1  14993
4 2018-03-08     jueves     1  15914

In [7]:
salesbehavior

time   %Sales WeekDay  %Sales Weekend
0       8        0.004435        0.002141
1       9        0.050000        0.014794
2      10        0.060000        0.032081
3      11        0.115565        0.053327
4      12        0.100000        0.087815
5      13        0.070000        0.071313
6      14        0.040000        0.077206
7      15        0.030000        0.072364
8      16        0.070000        0.086841
9      17        0.090000        0.119691
10     18        0.100000        0.115760
11     19        0.110000        0.125309
12     20        0.100000        0.099969
13     21        0.060000        0.041390

# Data manipulations

In [8]:
#DayWeek= {i:salesbehavior['%Sales WeekDay'][i] for i in range(len(salesbehavior['%Sales WeekDay']))}
#Weekeend= {i:salesbehavior['%Sales Weekend'][i] for i in range(len(salesbehavior['%Sales Weekend']))}
Weekeend=salesbehavior['%Sales Weekend'].values.flatten()
DayWeek=salesbehavior['%Sales WeekDay'].values.flatten()


In [9]:
DayWeek

array([0.0044348, 0.05     , 0.06     , 0.1155652, 0.1      , 0.07     ,
       0.04     , 0.03     , 0.07     , 0.09     , 0.1      , 0.11     ,
       0.1      , 0.06     ])

In [10]:
#Here we apply the desagregation of demand according to the day of the week
salesHour=[]
for i in range(len(sales['Sales'])):
    if (sales['Week Day'][i]=='domingo' or sales['Week Day'][i]=='sábado'):
        salesHour.append(sales['Sales'][i]*Weekeend)
    else:
        salesHour.append(sales['Sales'][i]*DayWeek)

print(type(salesHour))
len(salesHour)

<class 'list'>


30

In [11]:
#IN THIS PART, WE CALCULATE THE DEMAND OF PERSONNEL PER HOURS
import numpy as np
import math # Library used to round up numbers

empleRequirement=[]
for i in range(len(salesHour)):
    empleRequirement.append([math.ceil(num/1000) for num in salesHour[i]])

type(empleRequirement)



list

# Step 2: Building the model in CPLEX

In [12]:
from docplex.mp.model import Model
mdl=Model('PersonalScheduling')

### Initializing differents sets

In [14]:
Numshift = [i for i in range(len(Shift['Shift']))] #Num of Workshift 
Numhour = [i for i in range(len(Shift.columns[1:]))] #Num of hour in the workshift
workShiftNode = [(i,j) for i in Numshift for j in Numhour] # defining the numer of shift and the hours

#Initialization of shift matrix
s=[]
for i in Numshift:
    for j in Numhour:
        s.append(Shift.iloc[i][j+1])
                 
workShift = {workShiftNode[k]: s[k] for k in range(len(s))}

#Initialization of cost matrix
costShift=[CostShift['Shift Cost'][i] for i in Numshift]



### decraring the decision variable

In [15]:
X=mdl.integer_var_dict(Numshift,name = 'x')

In [16]:
#Objective function

mdl.minimize(mdl.sum(X[i]*costShift[i] for i in Numshift))

In [17]:
#demand must be satisfied
for j in Numhour:
    mdl.add_constraint(mdl.sum(X[k]*workShift[(k,j)] for k in Numshift)>=empleRequirement[0][j])

#full time workship must be assigne   
for i in range(7):
    mdl.add_constraint(X[i]>=1)

In [18]:
print(mdl.export_to_string())

\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: PersonalScheduling

Minimize
 obj: 40 x_0 + 40 x_1 + 40 x_2 + 40 x_3 + 40 x_4 + 40 x_5 + 40 x_6 + 20 x_7
      + 20 x_8 + 20 x_9 + 20 x_10 + 20 x_11 + 20 x_12 + 20 x_13 + 20 x_14
      + 20 x_15 + 20 x_16 + 20 x_17
Subject To
 c1: x_0 + x_7 >= 1
 c2: x_0 + x_1 + x_7 + x_8 >= 1
 c3: x_0 + x_1 + x_2 + x_7 + x_8 + x_9 >= 2
 c4: x_0 + x_1 + x_2 + x_3 + x_7 + x_8 + x_9 + x_10 >= 3
 c5: x_1 + x_2 + x_3 + x_4 + x_8 + x_9 + x_10 + x_11 >= 4
 c6: x_0 + x_2 + x_3 + x_4 + x_5 + x_9 + x_10 + x_11 + x_12 >= 4
 c7: x_0 + x_1 + x_3 + x_4 + x_5 + x_6 + x_10 + x_11 + x_12 + x_13 >= 4
 c8: x_0 + x_1 + x_2 + x_4 + x_5 + x_6 + x_11 + x_12 + x_13 + x_14 >= 4
 c9: x_0 + x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_12 + x_13 + x_14 + x_15 >= 4
 c10: x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_13 + x_14 + x_15 + x_16 >= 6
 c11: x_2 + x_3 + x_4 + x_5 + x_6 + x_14 + x_15 + x_16 + x_17 >= 6
 c12: x_3 + x_4 + x_5 + x_6 + x_15 + x_16 + x_17 >= 6
 c1

In [19]:
solucion=mdl.solve(log_output=True)

Version identifier: 20.1.0.0 | 2020-11-10 | 9bedb6d68
CPXPARAM_Read_DataCheck                          1
Found incumbent of value 1200.000000 after 0.06 sec. (0.00 ticks)
Tried aggregator 1 time.
MIP Presolve eliminated 21 rows and 18 columns.
All rows and columns eliminated.
Presolve time = 0.00 sec. (0.02 ticks)

Root node processing (before b&c):
  Real time             =    0.06 sec. (0.02 ticks)
Parallel b&c, 4 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    0.06 sec. (0.02 ticks)


In [20]:
mdl.get_solve_status()

<JobSolveStatus.OPTIMAL_SOLUTION: 2>

In [21]:
solucion.display()

solution for: PersonalScheduling
objective: 340
x_0 = 1
x_1 = 1
x_2 = 1
x_3 = 1
x_4 = 1
x_5 = 1
x_6 = 1
x_16 = 2
x_17 = 1


In [492]:
X[i].solution_value

1.0

In [23]:
#Store the solution in a dictionary data structure.
sol= {i: int(X[i].solution_value) for i in Numshift if X[i].solution_value > 0.9}
print(sol)

{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 16: 2, 17: 1}


# Step 3: PL assign the work shift to employees

In [101]:
from docplex.mp.model import Model
mdl2=Model('AssigPersonal')

In [102]:
#definir numero de nodos
numEmployee = [i for i in range(len(Availability['Employee']))]
numEmployee

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [103]:
Numshift = [i for i in range(len(Shift['Shift']))]
Numshift

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [104]:
#Store the solution in a dictionary data structure.
sol= {i: int(X[i].solution_value) for i in Numshift if X[i].solution_value > 0.9}
print(sol)

{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 16: 2, 17: 1}


In [105]:
#create set of variables
availaSet = [(i,j) for i in numEmployee for j in sol]
print(availaSet)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 16), (0, 17), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 16), (1, 17), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 16), (2, 17), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 16), (3, 17), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 16), (4, 17), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 16), (5, 17), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 16), (6, 17), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 16), (7, 17), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 16), (8, 17), (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 16), (9, 17), (10, 0), (10, 1), (10, 2), (10, 3), (10, 4), (10, 5), (10, 6), (10, 16), (10, 17), (11, 0), (11, 1), (11, 2), (11, 3), (11, 4), (11, 5), (11, 6), (11, 16), (11, 17), (12, 0), (12, 1), (12, 2), (12, 3), (12, 4), (12, 5), (12, 6), (12, 16), (12, 17), (13, 0), (

In [106]:
#create matrix for employee availability
#Here we read the worker disponibility
e=[]
for i in numEmployee:
    for j in Numshift:
        e.append(Availability.iloc[i][j+1])

availability = np.asarray(e,dtype= int) #Transform the list into array type  
availability = np.reshape(availability,(len(numEmployee),len(Numshift)))
print(availability)

[[1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1]]


In [107]:
#create desicion variable
Y=mdl2.binary_var_dict(availaSet,name = 'Y')

In [108]:
#Objective function
mdl2.maximize(mdl.sum(Y[i] for i in availaSet))

In [109]:
#We must assined the number of employee determined in the solutions
for j in sol:
    mdl2.add_constraint(mdl2.sum(Y[(i,j)] for i in numEmployee)==sol[j])

In [110]:
#every workshift must respect the employee disponibility
for i in numEmployee:
    mdl2.add_constraints(Y[(i,j)]<=100*availability[i][j] for j in sol)

In [111]:
#We must assined the number of employee determined in the solutions
for i in numEmployee:
    mdl2.add_constraint(mdl2.sum(Y[(i,j)] for j in sol)<=1)

In [112]:
print(mdl2.export_to_string())

\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: AssigPersonal

Maximize
 obj: Y_0_0 + Y_0_1 + Y_0_2 + Y_0_3 + Y_0_4 + Y_0_5 + Y_0_6 + Y_0_16 + Y_0_17
      + Y_1_0 + Y_1_1 + Y_1_2 + Y_1_3 + Y_1_4 + Y_1_5 + Y_1_6 + Y_1_16 + Y_1_17
      + Y_2_0 + Y_2_1 + Y_2_2 + Y_2_3 + Y_2_4 + Y_2_5 + Y_2_6 + Y_2_16 + Y_2_17
      + Y_3_0 + Y_3_1 + Y_3_2 + Y_3_3 + Y_3_4 + Y_3_5 + Y_3_6 + Y_3_16 + Y_3_17
      + Y_4_0 + Y_4_1 + Y_4_2 + Y_4_3 + Y_4_4 + Y_4_5 + Y_4_6 + Y_4_16 + Y_4_17
      + Y_5_0 + Y_5_1 + Y_5_2 + Y_5_3 + Y_5_4 + Y_5_5 + Y_5_6 + Y_5_16 + Y_5_17
      + Y_6_0 + Y_6_1 + Y_6_2 + Y_6_3 + Y_6_4 + Y_6_5 + Y_6_6 + Y_6_16 + Y_6_17
      + Y_7_0 + Y_7_1 + Y_7_2 + Y_7_3 + Y_7_4 + Y_7_5 + Y_7_6 + Y_7_16 + Y_7_17
      + Y_8_0 + Y_8_1 + Y_8_2 + Y_8_3 + Y_8_4 + Y_8_5 + Y_8_6 + Y_8_16 + Y_8_17
      + Y_9_0 + Y_9_1 + Y_9_2 + Y_9_3 + Y_9_4 + Y_9_5 + Y_9_6 + Y_9_16 + Y_9_17
      + Y_10_0 + Y_10_1 + Y_10_2 + Y_10_3 + Y_10_4 + Y_10_5 + Y_10_6 + Y_10_16
      + Y_10_17 + Y_

In [113]:
solucion2=mdl2.solve(log_output=True)

Version identifier: 20.1.0.0 | 2020-11-10 | 9bedb6d68
CPXPARAM_Read_DataCheck                          1
Found incumbent of value 10.000000 after 0.00 sec. (0.01 ticks)
Tried aggregator 1 time.
MIP Presolve eliminated 130 rows and 88 columns.
Reduced MIP has 19 rows, 38 columns, and 75 nonzeros.
Reduced MIP has 38 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.25 sec. (0.13 ticks)
Probing time = 0.01 sec. (0.02 ticks)
Tried aggregator 1 time.
MIP Presolve eliminated 7 rows and 15 columns.
Reduced MIP has 12 rows, 23 columns, and 46 nonzeros.
Reduced MIP has 23 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.03 sec. (0.03 ticks)
Probing time = 0.00 sec. (0.01 ticks)
Tried aggregator 1 time.
Detecting symmetries...
Reduced MIP has 12 rows, 23 columns, and 46 nonzeros.
Reduced MIP has 23 binaries, 0 generals, 0 SOSs, and 0 indicators.
Presolve time = 0.03 sec. (0.03 ticks)
Probing time = 0.00 sec. (0.01 ticks)
Clique table members: 12.
MIP emphasis: ba

In [114]:
mdl2.get_solve_status()

<JobSolveStatus.OPTIMAL_SOLUTION: 2>

In [115]:
solucion2.display()

solution for: AssigPersonal
objective: 10
Y_0_0 = 1
Y_1_1 = 1
Y_2_2 = 1
Y_3_3 = 1
Y_5_4 = 1
Y_7_5 = 1
Y_8_6 = 1
Y_10_16 = 1
Y_11_16 = 1
Y_12_17 = 1


# Step 3: Heuristic to assign the work shift to employees

In [465]:
Availability

Employee  S1  S2  S3  S4  S5  S6  S7  S8  S9  S10  S11  S12  S13  S14  \
0          1   0   0   0   0   1   1   1   0   0    0    0    0    0    0   
1          2   0   0   0   0   0   1   1   0   0    0    0    0    0    0   
2          3   0   0   0   0   1   1   1   0   0    0    0    0    0    0   
3          4   0   0   0   0   1   1   1   0   0    0    0    0    0    0   
4          5   0   0   0   0   0   0   0   0   0    0    0    0    0    0   
5          6   0   0   0   0   1   1   0   0   0    0    0    0    0    0   
6          7   0   0   0   0   0   0   0   0   0    0    0    0    0    0   
7          8   0   0   0   0   0   1   0   0   0    0    0    0    0    0   
8          9   0   0   0   0   0   0   1   0   0    0    0    0    0    0   
9         10   0   0   0   0   0   1   0   0   0    0    0    0    0    0   
10        11   0   0   0   0   0   0   0   1   1    1    0    1    1    1   
11        12   0   0   0   0   0   0   0   1   1    0    1    1    1    1   
12        13   0   0   0   0   0   0   0   1   1    1    1    0    1    1   
13        14   0   0   0   0   0   0   0   1   1    1    1    0    1    0   

    S15  S16  S17  S18  
0     0    0    0    0  
1     0    0    0    0  
2     0    0    0    0  
3     0    0    0    0  
4     0    0    0    0  
5     0    0    0    0  
6     0    0    0    0  
7     0    0    0    0  
8     0    0    0    0  
9     0    0    0    0  
10    1    1    1    1  
11    0    1    1    1  
12    1    1    1    1  
13    1    0    1    1

In [617]:
Numshift = [i for i in range(len(Shift['Shift']))]
Numshift

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [619]:
numEmployee = [i for i in range(len(Availability['Employee']))]
numEmployee

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [620]:
worshiftIndex = [i for i in sol]
print(worshiftIndex)

[0, 1, 2, 3, 4, 5, 6, 16, 17]


In [621]:
#Here we read the worker disponibility
e=[]
for i in numEmployee:
    for j in Numshift:
        e.append(Availability.iloc[i][j+1])

availability = np.asarray(e,dtype= int) #Transform the list into array type  
availability = np.reshape(availability,(len(numEmployee),len(Numshift)))
print(availability)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1]]


In [622]:
def empShift(emp,shift): #function that returns if a empleyee belongs to an espesific work shift
    if availability[emp][shift]==1:
        return True
    else:
        return False
schedule = {}
val=False
for j in sol:
    k=1
    while k <= sol[j]:
        for i in numEmployee:
            if empShift(i,j):
                schedule[i]=j
                print('emp',i,'turno:',j)
                numEmployee.remove(i)
                val = empShift(i,j)
            next
        k+=1
    if val:
        worshiftIndex.remove(j)
        
#noAsignado = {"na"&i: i for i in worshiftIndex}
print(schedule)
print(worshiftIndex)




emp 10 turno: 16
emp 12 turno: 16
emp 11 turno: 16
emp 13 turno: 17
{10: 16, 12: 16, 11: 16, 13: 17}
[0, 1, 2, 3, 4, 5, 6]


In [569]:
for i in schedule:
    print(schedule[i])

16
16
16
17


https://www.engineeringenotes.com/project-management-2/operations-research/assignment-problem-meaning-methods-and-variations-operations-research/15652